from bot.infra import events
from bot.infra.event_payloads import ReferralBonusGrantedPayload

from ._runtime import (
    WEBAPP_CSRF_COOKIE_NAME,
    WEBAPP_SESSION_COOKIE_NAME,
    WEBAPP_TELEGRAM_OAUTH_STATE_COOKIE_NAME,
    Any,
    AsyncSession,
    ClientTimeout,
    Dict,
    EmailAuthService,
    List,
    Optional,
    Settings,
    SubscriptionService,
    User,
    UserMergeConflictError,
    base64,
    create_signed_telegram_oauth_state,
    create_telegram_oauth_nonce,
    create_webapp_session_token,
    datetime,
    hashlib,
    hmac,
    ipaddress,
    is_disposable_email,
    logger,
    panel_description_from_profile,
    parse_ip_entries,
    re,
    sanitize_display_name,
    sanitize_username,
    secrets,
    security_dal,
    sessionmaker,
    subscription_dal,
    timezone,
    urlencode,
    urlsplit,
    user_dal,
    validate_telegram_login_widget_data,
    validate_telegram_oauth_id_token,
    validate_telegram_webapp_init_data,
    verify_signed_telegram_oauth_state,
    verify_telegram_oauth_nonce,
    web,
)
from .assets import (
    _enforce_webapp_rate_limit,
    _get_shared_http_session,
)
from .common import (
    _extract_authenticated_user_id,
    _format_webapp_datetime,
    _invalidate_webapp_user_caches,
    _json_error,
    _normalize_language,
    _parse_model_payload,
    _require_user_id,
    _resolve_telegram_oauth_client_id,
    _resolve_telegram_oauth_request_access,
    _telegram_id_for_user,
)
from .payloads import (
    WebAppEmailCodeAuthPayload,
    WebAppEmailMagicAuthPayload,
    WebAppEmailPasswordPayload,
    WebAppEmailRequestPayload,
    WebAppTelegramAuthPayload,
)
from .telegram_notifications import _probe_telegram_notifications_for_user_id

from .auth_common import (
    _build_webapp_auth_response,
    _clear_webapp_auth_cookies,
    _clear_telegram_oauth_state_cookie,
    _email_only_telegram_required_reason,
    _first_header_value,
    _hash_email_password,
    _normalize_referral_param,
    _panel_description_for_user,
    _password_hash_b64,
    _password_hash_unb64,
    _public_webapp_base_url,
    _read_telegram_oauth_state_payload,
    _referral_param_lookup_candidates,
    _referral_welcome_telegram_required_reason,
    _remnashop_referral_compat_enabled,
    _request_remote_is_trusted_proxy,
    _set_telegram_oauth_state_cookie,
    _set_webapp_auth_cookies,
    _strip_referral_param_prefix,
    _telegram_oauth_callback_url,
    _telegram_oauth_redirect_url,
    _telegram_photo_url_value,
    _trial_telegram_required_reason,
    _urlsafe_sha256,
    _user_has_linked_telegram,
    _verify_email_password,
)
from .auth_email import (
    _password_login_failure_response,
    _request_email_code,
    email_auth_magic_route,
    email_auth_request_route,
    email_auth_verify_route,
    email_password_auth_route,
)
from .auth_oauth import (
    _exchange_telegram_oauth_code,
    _validate_telegram_auth_payload,
    auth_token_route,
    logout_route,
    telegram_oauth_callback_route,
    telegram_oauth_nonce_route,
    telegram_oauth_start_route,
)
from .auth_panel import (
    _apply_telegram_profile_to_user,
    _build_account_merge_notice,
    _delete_merged_source_panel_user,
    _link_telegram_to_user,
    _sync_merged_panel_identity_for_user,
    _sync_panel_identity_for_user,
)
from .auth_referral import (
    _apply_referral_to_existing_user,
    _apply_referral_welcome_bonus_if_needed,
    _ensure_user_from_telegram,
    _grant_referral_welcome_bonus_if_eligible,
    _resolve_referrer_id,
    _webapp_datetime_text,
    referral_welcome_bonus_claim_route,
)
