"""Email settings manifest fields for the admin web app."""

from __future__ import annotations

from bot.app.web.admin_settings_manifest_types import SettingField

EMAIL_SETTINGS_FIELDS: tuple[SettingField, ...] = (
    SettingField(
        "QA_AUTH_ENABLED",
        "bool",
        "email",
        "QA email auth",
        (
            "Expose email verification codes through the public auth API in development "
            "and test runtimes. Production email login still requires SMTP."
        ),
        subsection="email_auth",
    ),
    SettingField(
        "WEBAPP_AUTH_MAX_AGE_SECONDS",
        "int",
        "email",
        "Web App auth max age",
        "Maximum age of a Web App auth session, in seconds.",
        optional=False,
        min=60,
        subsection="email_auth",
    ),
    SettingField(
        "WEBAPP_LOGIN_TOKEN_TTL_SECONDS",
        "int",
        "email",
        "Email magic link TTL",
        "Lifetime of one-time email login links and login tokens, in seconds.",
        optional=False,
        min=60,
        subsection="email_auth",
    ),
    SettingField(
        "SMTP_HOST",
        "string",
        "email",
        "SMTP host",
        (
            "SMTP server hostname. Email login turns on when host, port, username, "
            "password and from email are configured."
        ),
        placeholder="smtp-relay.brevo.com",
        subsection="smtp",
    ),
    SettingField(
        "SMTP_PORT",
        "int",
        "email",
        "SMTP port",
        "Primary SMTP port.",
        optional=False,
        min=1,
        max=65535,
        subsection="smtp",
    ),
    SettingField(
        "SMTP_FALLBACK_PORTS",
        "string",
        "email",
        "SMTP fallback ports",
        "Comma-separated fallback ports tried after the primary port.",
        placeholder="2525,465",
        subsection="smtp",
    ),
    SettingField(
        "SMTP_TIMEOUT_SECONDS",
        "int",
        "email",
        "SMTP timeout",
        "Network timeout for SMTP connections, in seconds.",
        optional=False,
        min=5,
        subsection="smtp",
    ),
    SettingField(
        "SMTP_USERNAME",
        "string",
        "email",
        "SMTP username",
        "Username used to authenticate with the SMTP server.",
        subsection="smtp",
    ),
    SettingField(
        "SMTP_PASSWORD",
        "string",
        "email",
        "SMTP password",
        "Password or API key used to authenticate with the SMTP server.",
        secret=True,
        subsection="smtp",
    ),
    SettingField(
        "SMTP_FROM_EMAIL",
        "string",
        "email",
        "From email",
        "Sender email address used for auth codes and notifications.",
        placeholder="noreply@example.com",
        subsection="smtp",
    ),
    SettingField(
        "SMTP_FROM_NAME",
        "string",
        "email",
        "From name",
        "Sender display name. Empty value falls back to the Web App title.",
        placeholder="My subscription",
        subsection="smtp",
    ),
    SettingField(
        "SMTP_STARTTLS",
        "bool",
        "email",
        "SMTP STARTTLS",
        "Upgrade plain SMTP connections with STARTTLS when SSL is not used.",
        optional=False,
        subsection="smtp",
    ),
    SettingField(
        "SMTP_USE_SSL",
        "bool",
        "email",
        "SMTP SSL",
        "Use implicit TLS/SSL for SMTP connections, usually on port 465.",
        optional=False,
        subsection="smtp",
    ),
    SettingField(
        "EMAIL_CODE_TTL_SECONDS",
        "int",
        "email",
        "Email code TTL",
        "How long email verification codes remain valid, in seconds.",
        optional=False,
        min=60,
        subsection="email_codes",
    ),
    SettingField(
        "EMAIL_CODE_RESEND_SECONDS",
        "int",
        "email",
        "Email code resend cooldown",
        "Minimum delay before a user can request another email code.",
        optional=False,
        min=1,
        subsection="email_codes",
    ),
    SettingField(
        "EMAIL_CODE_MAX_ATTEMPTS",
        "int",
        "email",
        "Email code max attempts",
        "Maximum verification attempts for one email code before it is rejected.",
        optional=False,
        min=1,
        subsection="email_codes",
    ),
    SettingField(
        "BRUTE_FORCE_MAX_FAILURES",
        "int",
        "email",
        "Failed attempts before lockout",
        "Maximum failed email or promo code attempts within the throttle window.",
        optional=False,
        min=1,
        subsection="email_security",
    ),
    SettingField(
        "BRUTE_FORCE_WINDOW_SECONDS",
        "int",
        "email",
        "Brute-force window",
        "Rolling window used to count failed email and promo code attempts, in seconds.",
        optional=False,
        min=60,
        subsection="email_security",
    ),
    SettingField(
        "BRUTE_FORCE_LOCK_SECONDS",
        "int",
        "email",
        "Brute-force lockout",
        "Temporary lockout duration after too many failed attempts, in seconds.",
        optional=False,
        min=1,
        subsection="email_security",
    ),
)
