"""Notification, backup, and support settings shown in the admin web app."""

from bot.app.web.admin_settings_manifest_types import SettingField

NOTIFICATION_SETTINGS_FIELDS: list[SettingField] = [
    SettingField(
        "SUBSCRIPTION_NOTIFICATIONS_ENABLED",
        "bool",
        "notifications",
        "Subscription Telegram notifications",
        "Send subscription lifecycle notifications to linked Telegram accounts.",
        subsection="notification_delivery",
    ),
    SettingField(
        "SUBSCRIPTION_EMAIL_NOTIFICATIONS_ENABLED",
        "bool",
        "notifications",
        "Subscription email notifications",
        (
            "When enabled, subscription lifecycle notifications are mirrored to linked user "
            "email addresses."
        ),
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_PAYMENTS_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Payment Telegram notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_PAYMENTS_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Payment email notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_TRAFFIC_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Traffic Telegram notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_TRAFFIC_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Traffic email notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICES_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Device Telegram notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICES_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Device email notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICE_ACTIVITY_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "New device Telegram notifications",
        "Notify a user when Remnawave registers a new HWID device.",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICE_ACTIVITY_EMAIL_ENABLED",
        "bool",
        "notifications",
        "New device email notifications",
        "Notify a user by email when Remnawave registers a new HWID device.",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICE_LIMIT_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Device limit Telegram notifications",
        "Notify a user when the last available HWID device slot is occupied.",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_DEVICE_LIMIT_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Device limit email notifications",
        "Notify a user by email when the last available HWID device slot is occupied.",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_SUPPORT_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Support Telegram notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_SUPPORT_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Support email notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_REFERRALS_TELEGRAM_ENABLED",
        "bool",
        "notifications",
        "Referral Telegram notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_REFERRALS_EMAIL_ENABLED",
        "bool",
        "notifications",
        "Referral email notifications",
        subsection="notification_delivery",
    ),
    SettingField(
        "USER_NOTIFICATION_SINGLE_CHANNEL_FALLBACK_ENABLED",
        "bool",
        "notifications",
        "Use the only linked channel as a fallback",
        (
            "When exactly one channel is selected but unavailable for a user, deliver through "
            "their only other linked channel. Both channels disabled always means no delivery."
        ),
        subsection="notification_delivery",
    ),
    SettingField(
        "SUBSCRIPTION_NOTIFY_ON_EXPIRE", "bool", "notifications", "Subscription Notify On Expire"
    ),
    SettingField(
        "SUBSCRIPTION_NOTIFY_AFTER_EXPIRE",
        "bool",
        "notifications",
        "Subscription Notify After Expire",
    ),
    SettingField(
        "SUBSCRIPTION_NOTIFY_DAYS_BEFORE",
        "int",
        "notifications",
        "Subscription Notify Days Before",
        min=0,
    ),
    SettingField(
        "SUBSCRIPTION_NOTIFY_HOURS_BEFORE",
        "int",
        "notifications",
        "Subscription Notify Hours Before",
        min=0,
        max=23,
    ),
    SettingField(
        "TORRENT_BLOCKER_NOTIFICATIONS_ENABLED",
        "bool",
        "notifications",
        "Torrent blocker notifications",
        "Notify local users when Remnawave confirms that their IP address was blocked.",
        subsection="torrent_blocker",
    ),
    SettingField(
        "TORRENT_BLOCKER_TELEGRAM_NOTIFICATIONS_ENABLED",
        "bool",
        "notifications",
        "Telegram notifications",
        "Send torrent blocker notifications to linked Telegram accounts.",
        subsection="torrent_blocker",
    ),
    SettingField(
        "TORRENT_BLOCKER_EMAIL_NOTIFICATIONS_ENABLED",
        "bool",
        "notifications",
        "Email notifications",
        "Mirror torrent blocker notifications to linked email addresses when SMTP is configured.",
        subsection="torrent_blocker",
    ),
    SettingField(
        "TORRENT_BLOCKER_NOTIFICATION_COOLDOWN_SECONDS",
        "int",
        "notifications",
        "Notification cooldown",
        (
            "Minimum seconds between repeated torrent blocker notifications to the same user and "
            "channel. Exact webhook duplicates are always suppressed."
        ),
        min=0,
        max=31536000,
        subsection="torrent_blocker",
    ),
    SettingField(
        "TORRENT_BLOCKER_NOTIFICATION_INCLUDE_IP",
        "bool",
        "notifications",
        "Show blocked IP address",
        (
            "Include the validated blocked IP address in the user notification. Disabled by "
            "default for privacy."
        ),
        subsection="torrent_blocker",
    ),
    SettingField("LOG_NEW_USERS", "bool", "notifications", "Log New Users"),
    SettingField("LOG_PAYMENTS", "bool", "notifications", "Log Payments"),
    SettingField("LOG_SUPPORT", "bool", "notifications", "Log Support"),
    SettingField("LOG_PROMO_ACTIVATIONS", "bool", "notifications", "Log Promo Activations"),
    SettingField("LOG_TRIAL_ACTIVATIONS", "bool", "notifications", "Log Trial Activations"),
    SettingField("LOG_SUSPICIOUS_ACTIVITY", "bool", "notifications", "Log Suspicious Activity"),
    SettingField(
        "LOG_ADMIN_ACTIONS",
        "bool",
        "notifications",
        "Log administrator actions",
        "When disabled, events from users listed in ADMIN_IDS are not stored in message logs.",
        i18n_label_key="admin_settings_field_log_admin_actions_label",
        i18n_description_key="admin_settings_field_log_admin_actions_description",
    ),
    SettingField(
        "LOG_LEVEL",
        "string",
        "notifications",
        "Log Level",
        "DEBUG / INFO / WARNING / ERROR",
    ),
    SettingField("LOG_CHAT_ID", "int", "notifications", "Log Chat ID"),
    SettingField("LOG_THREAD_ID", "int", "notifications", "Log Thread ID"),
    SettingField(
        "LOG_SUPPORT_THREAD_ID",
        "int",
        "notifications",
        "Support thread ID",
        "Log chat thread for support ticket notifications.",
    ),
    SettingField(
        "BACKUP_ENABLED",
        "bool",
        "backups",
        "Backups enabled",
        "The worker periodically builds a ZIP archive and sends it to Telegram.",
    ),
    SettingField(
        "BACKUP_CHAT_ID",
        "int",
        "backups",
        "Backup chat ID",
        "Where ZIP archives are sent. Falls back to LOG_CHAT_ID when empty.",
    ),
    SettingField(
        "BACKUP_THREAD_ID",
        "int",
        "backups",
        "Backup thread ID",
        "Optional topic/thread ID. Falls back to LOG_THREAD_ID when empty.",
    ),
    SettingField(
        "BACKUP_INTERVAL_SECONDS",
        "int",
        "backups",
        "Backup period (sec.)",
        "Default is 3600: run on the hour boundary (12:00, 13:00, etc.).",
        optional=False,
        min=60,
    ),
    SettingField(
        "BACKUP_LOCAL_RETENTION",
        "int",
        "backups",
        "Archives to keep",
        "How many latest ZIP archives to keep in data/backups on the server.",
        optional=False,
        min=1,
    ),
    SettingField(
        "BACKUP_COMPOSE_ENABLED",
        "bool",
        "backups",
        "Include compose folder",
        (
            "Adds a /app/compose-source snapshot. If the folder is not mounted, the DB "
            "backup is still created."
        ),
    ),
    SettingField(
        "SUPPORT_TICKETS_ENABLED",
        "bool",
        "support",
        "Support tickets enabled",
        "Enable the support tickets section in the user account and allow users to create tickets.",
    ),
    SettingField(
        "SUPPORT_ADMIN_EMAIL_NOTIFICATIONS_ENABLED",
        "bool",
        "support",
        "Admin email notifications",
        "When disabled, new tickets and user replies are sent only to Telegram and the log chat.",
    ),
    SettingField(
        "SUPPORT_ADMIN_NOTIFICATION_COOLDOWN_SECONDS",
        "int",
        "support",
        "Telegram notification cooldown",
        "Minimum seconds between repeated Telegram/log notifications for the same unread ticket.",
        min=0,
    ),
    SettingField(
        "SUPPORT_ADMIN_EMAIL_COOLDOWN_SECONDS",
        "int",
        "support",
        "Email notification cooldown",
        "Minimum seconds between repeated email notifications for the same unread ticket.",
        min=0,
    ),
    SettingField(
        "SUPPORT_TICKET_MAX_BODY_LENGTH",
        "int",
        "support",
        "Max message length",
        "Maximum number of characters in a ticket message.",
        min=1,
    ),
    SettingField(
        "SUPPORT_TICKET_MAX_SUBJECT_LENGTH",
        "int",
        "support",
        "Max subject length",
        "Maximum number of characters in a ticket subject.",
        min=1,
    ),
    SettingField(
        "SUPPORT_TICKET_RATE_LIMIT_PER_HOUR",
        "int",
        "support",
        "Ticket limit per hour",
        "How many new tickets a user can create per hour. 0 means unlimited.",
        min=0,
    ),
    SettingField(
        "SUPPORT_MESSAGE_RATE_LIMIT_PER_MINUTE",
        "int",
        "support",
        "Message limit per minute",
        "How many ticket messages a user may send per minute. 0 means unlimited.",
        min=0,
    ),
    SettingField(
        "SUPPORT_IMAGE_RATE_LIMIT_PER_DAY",
        "int",
        "support",
        "Image limit per day",
        "How many ticket image attachments a user may send per day. 0 means unlimited.",
        min=0,
    ),
]
