"""Introduce stable account identity and audited account roles."""

from sqlalchemy import text
from sqlalchemy.engine import Connection

from .engine import Migration


def _migration_0091_account_identity(connection: Connection) -> None:
    connection.execute(text("ALTER TABLE users ADD COLUMN IF NOT EXISTS account_id UUID"))
    connection.execute(
        text("UPDATE users SET account_id = gen_random_uuid() WHERE account_id IS NULL")
    )
    connection.execute(
        text("ALTER TABLE users ALTER COLUMN account_id SET DEFAULT gen_random_uuid()")
    )
    connection.execute(text("ALTER TABLE users ALTER COLUMN account_id SET NOT NULL"))
    connection.execute(
        text("CREATE UNIQUE INDEX IF NOT EXISTS uq_users_account_id ON users (account_id)")
    )
    connection.execute(
        text("""
        ALTER TABLE users ADD COLUMN IF NOT EXISTS minishop_id VARCHAR(35)
        GENERATED ALWAYS AS ('ms_' || replace(CAST(account_id AS VARCHAR), '-', '')) STORED
    """)
    )
    connection.execute(
        text("CREATE UNIQUE INDEX IF NOT EXISTS uq_users_minishop_id ON users (minishop_id)")
    )
    connection.execute(
        text("ALTER TABLE users ADD COLUMN IF NOT EXISTS panel_username VARCHAR(255)")
    )
    connection.execute(
        text("""
        ALTER TABLE users ADD COLUMN IF NOT EXISTS panel_username_state VARCHAR(32)
        NOT NULL DEFAULT 'unverified'
    """)
    )
    connection.execute(
        text("""
        CREATE TABLE IF NOT EXISTS account_roles (
            user_id BIGINT NOT NULL REFERENCES users(user_id),
            role VARCHAR(16) NOT NULL CHECK (role IN ('owner', 'admin')),
            granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            granted_by BIGINT REFERENCES users(user_id),
            revoked_at TIMESTAMPTZ,
            revoked_by BIGINT REFERENCES users(user_id),
            PRIMARY KEY (user_id, role)
        )
    """)
    )
    connection.execute(
        text("""
        CREATE TABLE IF NOT EXISTS account_role_events (
            event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(user_id),
            role VARCHAR(16) NOT NULL CHECK (role IN ('owner', 'admin')),
            action VARCHAR(16) NOT NULL CHECK (action IN ('grant', 'revoke')),
            actor_user_id BIGINT REFERENCES users(user_id),
            source VARCHAR(32) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    )
    connection.execute(
        text("""
        CREATE TABLE IF NOT EXISTS account_aliases (
            old_user_id BIGINT PRIMARY KEY,
            new_user_id BIGINT NOT NULL REFERENCES users(user_id),
            reason VARCHAR(64) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    )
    connection.execute(
        text("""
        CREATE TABLE IF NOT EXISTS account_role_legacy_migrations (
            source VARCHAR(32) PRIMARY KEY,
            unresolved_count INTEGER NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    )


CHAIN_0091_ACCOUNT_IDENTITY: list[Migration] = [
    Migration(
        id="0091_account_identity",
        description="Add immutable UUID identity, panel username tracking, and audited roles",
        upgrade=_migration_0091_account_identity,
    )
]
