"""Branded HTML email template public facade."""

from __future__ import annotations

from .email_templates_auth import render_account_merged, render_login_code
from .email_templates_common import (
    EmailContent,
    EmailInlineImage,
    _ANY_TAG_RE,
    _ALLOWED_INLINE_TAGS,
    _BG,
    _BORDER,
    _CARD_BG,
    _DEFAULT_ACCENT,
    _EMAIL_LOGO_BACKGROUND,
    _EMAIL_LOGO_CONTENT_ID,
    _EMAIL_LOGO_DISPLAY_SIZE,
    _EMAIL_LOGO_RASTER_PADDING,
    _EMAIL_LOGO_RASTER_SIZE,
    _EMAIL_LOGO_SAFE_RASTER_EXTENSIONS,
    _HEX_RE,
    _INLINE_TAG_RE,
    _LOGO_CONTENT_TYPES,
    _TEXT,
    _TEXT_DIM,
    _TEXT_MUTED,
    _UPLOADED_LOGO_RE,
    _WEBAPP_LOGO_MAX_BYTES,
    _WEBAPP_UPLOADED_LOGO_DIR,
    _WEBAPP_UPLOADED_LOGO_PATH,
    _EmailLayout,
    _brand_title,
    _crop_transparent_logo_padding,
    _cta_button_html,
    _email_content,
    _email_logo,
    _email_logo_payload,
    _email_safe_raster_logo_to_png,
    _format_amount,
    _format_minutes,
    _format_traffic,
    _hex_to_rgba,
    _info_rows_html,
    _inline_uploaded_logo,
    _layout,
    _normalize_lang,
    _public_logo_url,
    _resolve_i18n,
    _safe_color,
    _t_html,
    _t_text,
    _telegram_html_to_email_html,
    _telegram_html_to_text,
    _theme_accent,
    _uploaded_logo_dir,
    _uploaded_logo_filename,
)
from .email_templates_notifications import (
    _subscription_lifecycle_title,
    render_subscription_expiring,
    render_subscription_lifecycle_notification,
    render_user_notification,
)
from .email_templates_payments import render_payment_success
from .email_templates_support import (
    _support_email,
    render_support_admin_reply_user,
    render_support_new_ticket_admin,
    render_support_ticket_closed_user,
    render_support_user_reply_admin,
)

__all__ = [
    "EmailContent",
    "EmailInlineImage",
    "render_account_merged",
    "render_login_code",
    "render_payment_success",
    "render_subscription_expiring",
    "render_subscription_lifecycle_notification",
    "render_support_admin_reply_user",
    "render_support_new_ticket_admin",
    "render_support_ticket_closed_user",
    "render_support_user_reply_admin",
    "render_user_notification",
]
