import type { PreviewTheme, PreviewThemeTokens } from "./types";

export const DEFAULT_THEME_VARIANTS: Record<string, PreviewThemeTokens> = {
  dark: {
    color_scheme: "dark",
    accent: "#00fe7a",
    accent_contrast: "#001f10",
    bg: "#03070b",
    panel: "#111820",
    panel_2: "#0b1118",
    panel_3: "#17212b",
    text: "#f2f7f4",
    muted: "#a9b4b0",
    dim: "#68736f",
    border: "rgba(255,255,255,0.08)",
    border_strong: "rgba(255,255,255,0.16)",
    danger: "#ff6b6b",
    danger_text: "#ffb4b4",
    danger_soft: "color-mix(in srgb, var(--danger) 12%, var(--panel))",
    danger_border: "color-mix(in srgb, var(--danger) 34%, var(--border))",
    success: "#3ecf8e",
    success_text: "#7ff0b9",
    success_soft: "color-mix(in srgb, var(--success) 12%, var(--panel))",
    success_border: "color-mix(in srgb, var(--success) 34%, var(--border))",
    warning: "#ffd166",
    warning_text: "#ffd166",
    warning_soft: "color-mix(in srgb, var(--warning) 12%, var(--panel))",
    warning_border: "color-mix(in srgb, var(--warning) 34%, var(--border))",
    info: "#2d9cff",
    info_text: "#8ed0ff",
    info_soft: "color-mix(in srgb, var(--info) 12%, var(--panel))",
    info_border: "color-mix(in srgb, var(--info) 34%, var(--border))",
    surface_hover: "rgba(255,255,255,0.07)",
    surface_muted: "rgba(255,255,255,0.04)",
    nav_bg: "rgba(3,7,11,0.9)",
    rail_bg: "rgba(7,11,18,0.92)",
    shadow_soft: "0 18px 48px rgba(0,0,0,0.22)",
    shadow_strong: "0 26px 70px rgba(0,0,0,0.46)",
    shadow_popover: "0 20px 34px rgba(0,0,0,0.42)",
    inset_highlight: "rgba(255,255,255,0.05)",
    radius: "8px",
    font_family: "Inter, Arial, sans-serif",
    mono_font_family: '"JetBrains Mono", Consolas, monospace',
  },
  light: {
    color_scheme: "light",
    accent: "#047857",
    accent_contrast: "#ffffff",
    bg: "#f7f8fb",
    panel: "#ffffff",
    panel_2: "#f1f5f9",
    panel_3: "#e8edf3",
    text: "#0b1220",
    muted: "#3f4b5f",
    dim: "#526174",
    border: "rgba(15,23,42,0.14)",
    border_strong: "rgba(15,23,42,0.26)",
    danger: "#b91c1c",
    danger_text: "#991b1b",
    danger_soft: "color-mix(in srgb, var(--danger) 9%, var(--panel))",
    danger_border: "color-mix(in srgb, var(--danger) 34%, var(--border))",
    success: "#047857",
    success_text: "#065f46",
    success_soft: "color-mix(in srgb, var(--success) 10%, var(--panel))",
    success_border: "color-mix(in srgb, var(--success) 34%, var(--border))",
    warning: "#a16207",
    warning_text: "#854d0e",
    warning_soft: "color-mix(in srgb, var(--warning) 11%, var(--panel))",
    warning_border: "color-mix(in srgb, var(--warning) 34%, var(--border))",
    info: "#1d4ed8",
    info_text: "#1e40af",
    info_soft: "color-mix(in srgb, var(--info) 9%, var(--panel))",
    info_border: "color-mix(in srgb, var(--info) 30%, var(--border))",
    surface_hover: "rgba(15,23,42,0.055)",
    surface_muted: "rgba(15,23,42,0.04)",
    nav_bg: "rgba(255,255,255,0.94)",
    rail_bg: "rgba(255,255,255,0.9)",
    shadow_soft: "0 8px 24px rgba(15,23,42,0.07)",
    shadow_strong: "0 18px 46px rgba(15,23,42,0.11)",
    shadow_popover: "0 14px 30px rgba(15,23,42,0.11)",
    inset_highlight: "rgba(255,255,255,0.75)",
    radius: "8px",
    font_family: "Inter, Arial, sans-serif",
    mono_font_family: '"JetBrains Mono", Consolas, monospace',
  },
};

export const DEFAULT_DARK_THEME: PreviewTheme = {
  key: "dark",
  names: { ru: "По умолчанию", en: "Default" },
  enabled: true,
  default: true,
  assets_version: 3,
  active_variant: "dark",
  tokens: DEFAULT_THEME_VARIANTS.dark,
  variants: DEFAULT_THEME_VARIANTS,
};

export const LEGACY_LIGHT_THEME: PreviewTheme = {
  key: "light",
  names: { ru: "Светлая", en: "Light" },
  enabled: true,
  default: false,
  hidden: true,
  active_variant: "light",
  variant_alias_for: "dark",
  tokens: DEFAULT_THEME_VARIANTS.light,
};

export const WINDOWS_95_THEME: PreviewTheme = {
  key: "windows95",
  names: { ru: "Windows 95", en: "Windows 95" },
  enabled: true,
  default: false,
  css_file: "style.css",
  assets_version: 16,
  active_variant: "light",
  tokens: {
    color_scheme: "light",
    style_preset: "win95",
  },
  variants: {
    light: { color_scheme: "light" },
    dark: { color_scheme: "dark" },
  },
};

export const ASCII_THEME: PreviewTheme = {
  key: "ascii",
  names: { ru: "ASCII", en: "ASCII" },
  enabled: true,
  default: false,
  css_file: "style.css",
  assets_version: 9,
  active_variant: "dark",
  tokens: {
    color_scheme: "dark",
    style_preset: "ascii",
  },
  variants: {
    light: { color_scheme: "light" },
    dark: { color_scheme: "dark" },
  },
};
