"""Admin settings manifest for RollyPay."""

from __future__ import annotations

from ..base import ProviderManifestField

CONFIG_MANIFEST: tuple[ProviderManifestField, ...] = (
    ProviderManifestField(
        "ROLLYPAY_ENABLED",
        "bool",
        "Enabled",
        subsection="RollyPay",
        attr="ENABLED",
    ),
    ProviderManifestField(
        "ROLLYPAY_BASE_URL",
        "url",
        "Base URL",
        placeholder="https://rollypay.io/api/v1",
        subsection="RollyPay",
        attr="BASE_URL",
    ),
    ProviderManifestField(
        "ROLLYPAY_API_KEY",
        "string",
        "API key",
        secret=True,
        subsection="RollyPay",
        attr="API_KEY",
    ),
    ProviderManifestField(
        "ROLLYPAY_SIGNING_SECRET",
        "string",
        "Webhook secret",
        secret=True,
        subsection="RollyPay",
        attr="SIGNING_SECRET",
    ),
    ProviderManifestField(
        "ROLLYPAY_TERMINAL_ID",
        "string",
        "Terminal ID",
        subsection="RollyPay",
        attr="TERMINAL_ID",
    ),
    ProviderManifestField(
        "ROLLYPAY_ALL_METHODS_ENABLED",
        "bool",
        "Hosted method chooser",
        subsection="RollyPay",
        attr="ALL_METHODS_ENABLED",
        i18n_label_key="admin_settings_field_rollypay_all_methods_enabled_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_SBP_ENABLED",
        "bool",
        "SBP button",
        subsection="RollyPay",
        attr="SBP_ENABLED",
    ),
    ProviderManifestField(
        "ROLLYPAY_CARD_ENABLED",
        "bool",
        "Card button",
        subsection="RollyPay",
        attr="CARD_ENABLED",
        i18n_label_key="admin_settings_field_rollypay_card_enabled_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_INTERNATIONAL_ENABLED",
        "bool",
        "International card button",
        subsection="RollyPay",
        attr="INTERNATIONAL_ENABLED",
        i18n_label_key="admin_settings_field_rollypay_international_enabled_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_CRYPTO_ENABLED",
        "bool",
        "Crypto button",
        subsection="RollyPay",
        attr="CRYPTO_ENABLED",
    ),
    ProviderManifestField(
        "ROLLYPAY_SUBSCRIPTION_ENABLED",
        "bool",
        "Recurring SBP subscription",
        subsection="RollyPay",
        attr="SUBSCRIPTION_ENABLED",
        i18n_label_key="admin_settings_field_rollypay_subscription_enabled_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_TEST_MODE",
        "bool",
        "Test mode",
        subsection="RollyPay",
        attr="TEST_MODE",
    ),
    ProviderManifestField(
        "ROLLYPAY_SUCCESS_URL",
        "url",
        "Success URL",
        subsection="RollyPay",
        attr="SUCCESS_URL",
    ),
    ProviderManifestField(
        "ROLLYPAY_FAIL_URL",
        "url",
        "Fail URL",
        subsection="RollyPay",
        attr="FAIL_URL",
    ),
    ProviderManifestField(
        "ROLLYPAY_WEBHOOK_TOLERANCE_SECONDS",
        "int",
        "Webhook tolerance seconds",
        subsection="RollyPay",
        attr="WEBHOOK_TOLERANCE_SECONDS",
        min=30,
        max=3600,
    ),
    ProviderManifestField(
        "ROLLYPAY_WEBHOOK_LOOKUP_TIMEOUT_SECONDS",
        "float",
        "Webhook lookup timeout",
        subsection="RollyPay",
        attr="WEBHOOK_LOOKUP_TIMEOUT_SECONDS",
        min=1,
        max=9,
        i18n_label_key="admin_settings_field_rollypay_webhook_lookup_timeout_seconds_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_PLAN_CACHE_SECONDS",
        "int",
        "Recurring plan cache",
        subsection="RollyPay",
        attr="PLAN_CACHE_SECONDS",
        min=30,
        max=3600,
        i18n_label_key="admin_settings_field_rollypay_plan_cache_seconds_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_RECONCILE_INTERVAL_SECONDS",
        "int",
        "Subscription reconciliation interval",
        subsection="RollyPay",
        attr="RECONCILE_INTERVAL_SECONDS",
        min=60,
        i18n_label_key="admin_settings_field_rollypay_reconcile_interval_seconds_label",
    ),
    ProviderManifestField(
        "ROLLYPAY_RECONCILE_BATCH_SIZE",
        "int",
        "Subscription reconciliation batch",
        subsection="RollyPay",
        attr="RECONCILE_BATCH_SIZE",
        min=1,
        max=500,
        i18n_label_key="admin_settings_field_rollypay_reconcile_batch_size_label",
    ),
)


__all__ = ["CONFIG_MANIFEST"]
