from __future__ import annotations

import argparse
import json
import os
import re
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Final, cast

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT: Final = REPO_ROOT / "backend" / "config" / "disposable_email_blocklist.conf"
DOMAIN_LABEL_RE: Final = re.compile(r"^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")
PROTECTED_DOMAINS: Final = {
    "gmail.com",
    "googlemail.com",
    "icloud.com",
    "mail.ru",
    "outlook.com",
    "proton.me",
    "protonmail.com",
    "yahoo.com",
    "yandex.com",
    "yandex.ru",
}
REVIEWED_SUPPLEMENTS: Final = {
    "ogzmail.com",
    "prorises.com",
}


@dataclass(frozen=True)
class BlocklistSource:
    repository: str
    branch: str
    path: str
    license_name: str
    minimum_domains: int


SOURCES: Final = (
    BlocklistSource(
        repository="disposable-email-domains/disposable-email-domains",
        branch="main",
        path="disposable_email_blocklist.conf",
        license_name="CC0-1.0",
        minimum_domains=5_000,
    ),
    BlocklistSource(
        repository="castle/disposable-email-domains",
        branch="master",
        path="disposable-email-domains.txt",
        license_name="MIT",
        minimum_domains=500,
    ),
)


def _request_text(url: str, *, token: str | None = None) -> str:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "remnawave-minishop-blocklist-updater",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        body = cast(bytes, response.read())
        return body.decode("utf-8")


def _resolve_commit(source: BlocklistSource, *, token: str | None) -> str:
    url = f"https://api.github.com/repos/{source.repository}/commits/{source.branch}"
    payload = cast(dict[str, object], json.loads(_request_text(url, token=token)))
    sha = str(payload.get("sha") or "").strip().lower()
    if not re.fullmatch(r"[0-9a-f]{40}", sha):
        raise RuntimeError(f"GitHub returned an invalid commit for {source.repository}")
    return sha


def _is_domain(value: str) -> bool:
    if len(value) > 253 or "." not in value:
        return False
    labels = value.split(".")
    return all(DOMAIN_LABEL_RE.fullmatch(label) for label in labels)


def _parse_domains(text: str, *, source: BlocklistSource) -> set[str]:
    domains: set[str] = set()
    invalid: list[str] = []
    for raw_line in text.splitlines():
        domain = raw_line.strip().lower().lstrip("@.")
        if not domain or domain.startswith("#"):
            continue
        try:
            domain = domain.encode("idna").decode("ascii")
        except UnicodeError:
            invalid.append(raw_line.strip())
            continue
        if not _is_domain(domain):
            invalid.append(raw_line.strip())
            continue
        domains.add(domain)

    if invalid:
        sample = ", ".join(repr(item) for item in invalid[:5])
        raise RuntimeError(f"Invalid domains from {source.repository}: {sample}")
    if len(domains) < source.minimum_domains:
        raise RuntimeError(
            f"Refusing unexpectedly small list from {source.repository}: "
            f"{len(domains)} < {source.minimum_domains}"
        )
    protected = sorted(PROTECTED_DOMAINS.intersection(domains))
    if protected:
        raise RuntimeError(
            f"Protected mailbox providers appeared in {source.repository}: {', '.join(protected)}"
        )
    return domains


def _render_snapshot(resolved_sources: list[tuple[BlocklistSource, str, set[str]]]) -> str:
    domains = set(REVIEWED_SUPPLEMENTS)
    header = [
        "# Generated by scripts/update_disposable_email_blocklist.py. Do not edit manually.",
        "# The application uses this vendored snapshot and never downloads lists at runtime.",
    ]
    for source, commit, source_domains in resolved_sources:
        domains.update(source_domains)
        header.append(
            f"# Source: https://github.com/{source.repository}/commit/{commit} "
            f"({source.license_name})."
        )
    header.append(f"# Reviewed supplements: {', '.join(sorted(REVIEWED_SUPPLEMENTS))}.")
    return "\n".join([*header, "", *sorted(domains), ""])


def update_snapshot(output: Path) -> bool:
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    resolved_sources: list[tuple[BlocklistSource, str, set[str]]] = []
    for source in SOURCES:
        commit = _resolve_commit(source, token=token)
        raw_url = f"https://raw.githubusercontent.com/{source.repository}/{commit}/{source.path}"
        domains = _parse_domains(_request_text(raw_url), source=source)
        resolved_sources.append((source, commit, domains))

    rendered = _render_snapshot(resolved_sources)
    current = output.read_text(encoding="utf-8") if output.exists() else None
    if current == rendered:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh the vendored disposable-email domain snapshot."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    changed = update_snapshot(args.output.resolve())
    print("Disposable-email blocklist updated." if changed else "Blocklist is already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
